### ISSUE TITLE
Support MCP23008

### ISSUE THREAD

**Issue by errzett** [UncleSamSwiss/ioBroker.i2c#10]
Hallo UncleSamSwiss,

kannst Du bitte den MCP23008 mit aufnehmen?
Oder kann man die Datei vom MCP23017 relativ einfach anpassen?

Vielen Dank schon mal

**Comment by UncleSamSwiss** [comment]
Hallo @errzett 

Werde ich in den nächsten Tagen machen. Da ich keinen MCP23008 zur Verfügung habe, bin ich dann auf dich für's Testen angewiesen.
Ich melde mich hier, sobald ich etwas testbares habe.

/UncleSam

**Comment by UncleSamSwiss** [comment]
Ich habe eine erste Version erstellt. Kannst du bitte mal versuchen, den Adapter von folgender URL zu installieren (mit dem Katzen-Symbol im ioBroker.admin):
https://github.com/UncleSamSwiss/ioBroker.i2c/tarball/develop

Ich warte auf dein Feedback bis ich die Änderungen veröffentliche.

**Comment by errzett** [comment]
Hallo UncleSamSwiss,

getestet und für perfekt befunden! Danke schön.
Die Ausgänge musste ich auf invertiert einstellen aber ich denke das muss so sein.
Bisher keine Fehlermeldungen im Log. 

Vielen Dank
errzett

**Comment by UncleSamSwiss** [comment]
Danke für das Feedback, damit schliesse ich diesen Issue.
