### ISSUE TITLE
Update stable version in repo from 1.1.1 to 1.2.0

### ISSUE THREAD

**Issue by GermanBluefox** [UncleSamSwiss/ioBroker.i2c#154]
# Think about update stable version to 1.2.0
**Version**: stable=**1.1.1** (108 days old) => latest=**1.2.0** (15 days old)
**Installs**: stable=**275** (69.44%), latest=**46** (11.62%), total=**396**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L572)

**Comment by UncleSamSwiss** [comment]
Done.
