### ISSUE TITLE
BME280 doesn't work

### ISSUE THREAD

**Issue by crone66** [UncleSamSwiss/ioBroker.i2c#17]
Hi I get this error message when using a BME280 sensor.

Log:
host.raspberrypi | 2019-03-29 19:49:16.326 | error | instance system.adapter.i2c.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-03-29 19:49:16.326 | error | by controller[0]: at Decoder.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15) errno: 121, code: '', syscall: 'writeByteSync' }
Caught | 2019-03-29 19:49:16.326 | error | by controller[0]: at Manager.ondecoded (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/manager.js:345:8)
Caught | 2019-03-29 19:49:16.326 | error | by controller[0]: at Manager.Emitter.emit (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/component-emitter/index.js:133:20)
Caught | 2019-03-29 19:49:16.326 | error | by controller[0]: at Manager.<anonymous> (/opt/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2019-03-29 19:49:16.326 | error | by controller[0]: at Socket.onpacket (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:244:12)
Caught | 2019-03-29 19:49:16.325 | error | by controller[0]: at Socket.onack (/opt/iobroker/node_modules/iobroker.js-controller/node_modules/socket.io-client/lib/socket.js:319:9)
Caught | 2019-03-29 19:49:16.325 | error | by controller[0]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.i2c/devices/BME280.js:184:37)
Caught | 2019-03-29 19:49:16.325 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.i2c/devices/BME280.js:95:34
Caught | 2019-03-29 19:49:16.325 | error | by controller[0]: at BME280.checkChipId (/opt/iobroker/node_modules/iobroker.i2c/devices/BME280.js:192:25)
Caught | 2019-03-29 19:49:16.325 | error | by controller[0]: at Bus.writeByteSync (/opt/iobroker/node_modules/iobroker.i2c/node_modules/i2c-bus/i2c-bus.js:257:7)
Caught | 2019-03-29 19:49:16.324 | error | by controller[0]: { Error: , Remote I/O error

**Comment by UncleSamSwiss** [comment]
It looks like the BME280 was connected correctly when you added it in ioBroker, but later you disconnected it (or changed its address). Please verify you can still detect the BME280 properly:
1. Remove it in the adapter configuration
2. Try to search again, if you find it, it should work again

**Comment by crone66** [comment]
After I switched my jumper wires one by one I found out that one of them doesn't work properly. Now everything works as it should. Thank you.
