### ISSUE TITLE
Support for DAC MCP4725

### ISSUE THREAD

**Issue by juamiso** [UncleSamSwiss/ioBroker.i2c#20]
I need to output an analog voltage to control a battery charger. I got this chip already running with a python script but it seems very difficult to access this script via blocky/javascript so could you please supoort this chip in your module ? address is 0x60

**Comment by UncleSamSwiss** [comment]
Waiting for hardware:
one MCP4725 ordered at AliExpress, expected delivery in 30-50 days,

**Comment by juamiso** [comment]
Good! Waiting for the module :)
I am trying to connect ADS1015 but the adapter finds nothing, see:

i2c.0 | 2019-05-15 22:30:46.132 | info | Search found: []
i2c.0 | 2019-05-15 22:30:36.414 | info | starting. Version 0.0.6 in /opt/iobroker/node_modules/iobroker.i2c, node: v8.16.0

However there is in the bus (4a). why is this happening?
pi@ioBroker-Pi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- 4a -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 -- -- -- -- -- -- -- 68 69 -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --

**Comment by UncleSamSwiss** [comment]
Apparently there is an issue with access rights. Your user "pi" has the rights to access the I2C bus while the user running ioBroker (probably "iobroker", but check your `ps -aux`) doesn't have these rights. The following command may solve the issue (I haven't tested it myself):
`sudo usermod -G i2c iobroker`

**Comment by juamiso** [comment]
> Apparently there is an issue with access rights. Your user "pi" has the rights to access the I2C bus while the user running ioBroker (probably "iobroker", but check your `ps -aux`) doesn't have these rights. The following command may solve the issue (I haven't tested it myself):
> `sudo usermod -G i2c iobroker`

This fixed it. I am now able to read ADS1115  Thanks x1000

**Comment by UncleSamSwiss** [comment]
Unfortunately shipping with Yanwen didn't work. Reordered today, expected delivery in 30-50 days

**Comment by UncleSamSwiss** [comment]
Package arrived from China... I will implement it soon.
