### ISSUE TITLE
Support for HMC5883L / QMC5883L

### ISSUE THREAD

**Issue by UncleSamSwiss** [UncleSamSwiss/ioBroker.i2c#21]
From https://forum.iobroker.net/post/227470:
> ich lese meinen Gaszähler aktuell auf folgende Art aus:
> https://www.kompf.de/tech/gascountmag.html
>
>Dies funktioniert recht gut, jedoch würde ich mich auch sehr freuen, wenn ich den Sensor (Magnetometer HMC5883) direkt im iobroker verwenden könnte, und die Skripte somit im iobroker laufen. Lässt sich der Sensor denn auch irgendwie in den Adapter einbinden?

**Comment by UncleSamSwiss** [comment]
Waiting for hardware:
one HMC5883L ordered at AliExpress, expected delivery in 30-50 days,

**Comment by flubb86** [comment]
HMC5883L already arrived? Do you know when you will realize it?

**Comment by UncleSamSwiss** [comment]
Unfortunately shipping with Yanwen didn't work. Reordered today, expected delivery in 30-50 days

**Comment by UncleSamSwiss** [comment]
Package arrived from China... I will implement it soon.

**Comment by hacki11** [comment]
i can provide the implementation for the QMC5883 (small difference but easier to get here) after the hmc is finished.

(then my python script will be obsolete and i can read directly in iobroker)
https://github.com/hacki11/qmc5883-gas-meter

**Comment by flubb86** [comment]
@UncleSamSwiss Bist du noch aktiv? Bzw. wird der Adapter noch weiterentwickelt? Thx

**Comment by UncleSamSwiss** [comment]
@flubb86 Sorry für die späte Antwort. Ab sofort arbeite ich wieder an meinen Adaptern und werde wahrscheinlich Mitte August neue Hardware unterstützen.

**Comment by UncleSamSwiss** [comment]
@hacki11 Thanks for your support, I'll let you know once I finished the HMC5883 implementation to see what changes are needed.

**Comment by UncleSamSwiss** [comment]
Unfortunately the IC I received is a QMC5883L (bus address 0x0D). I will implement this device for now. Does anybody still require the original HMC5883L (0x1E)?

**Comment by hacki11** [comment]
Can help to implement, looking forward supporting this model
