### ISSUE TITLE
SX1509 input long reaction time

### ISSUE THREAD

**Issue by grooovie** [UncleSamSwiss/ioBroker.i2c#239]
I use SX1509 on Iobroker 
PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:2304 MHz
Modell:Common KVM processor
RAM:7.7 GB
System-Betriebszeit:32 T. 21:58:03
Node.js:v12.22.1
NPM:6.14.12
Datenträgergröße:30.0 GB
Festplatte frei:23.3 GB
Adapter-Anzahl:418
Betriebszeit:1 T. 01:21:41
Aktive Instanzen:23
Pfad:/opt/iobroker/

and i2c module 1.2
javascript 4.6.17

preference i have
- no debounce
- 1ms polling
- falling edge triggerd
- pull up mode

wired is a button from GND to the input pin

by pressing the button there is no reaction to see in the object sates

by holding presse about half second the state in the objects is changing

this is a bit to long for my buttons. for example to turn on light you have to hold almost a second the button.

is there a bug or wrong preferences ? please help

**Comment by UncleSamSwiss** [comment]
There is almost no way a 1 ms polling interval will work properly.

I suggest you increase the polling interval to something more bearable for your CPU. A human finger has a "resolution" of about 10 to 15 ms minimum. The human eye will not detect a delay if you react within about 50 - 100ms. In my house, I'm using a 100ms polling interval and it still seems like the light goes on instantly.

If you need high precision resolution, think about using the interrupt line and connect it to a pin directly on your device, then choose the interrupt source accordingly in the i2c adapter configuration.
