### ISSUE TITLE
no reaction on bus scan

### ISSUE THREAD

**Issue by cyberax17** [UncleSamSwiss/ioBroker.i2c#25]
Hi, if I klick on search devices nothing happens.
The i2c adapter instance apears red in iobroker.
i2c works as a charm directly on the console (i2cdetect).

iobroker version 1.5.11
nodejs 8.15.1
npm 6.4.1

What am I doing wrong?

Cheers and thanks for your help in advance!

**Comment by UncleSamSwiss** [comment]
Sorry for the late answer. If it's read, it means the adapter can't start. Please check the log (perhaps set the level to "Debug"):
https://github.com/UncleSamSwiss/ioBroker.i2c#bug-reports-and-feature-requests

If the adapter starts (green icon), but you still don't see anything, have a look at this chapter:
https://github.com/UncleSamSwiss/ioBroker.i2c#access-right-issue

**Comment by UncleSamSwiss** [comment]
No answer. Closing the issue for now.
