### ISSUE TITLE
Support for SRF02

### ISSUE THREAD

**Issue by Christoph-1982** [UncleSamSwiss/ioBroker.i2c#26]
Hättest du Lust den SRF02 Ultraschallsensor einzubinden ? Ich würde gerne damit meinen Regenwassertankinhalt auslesen.

**Comment by UncleSamSwiss** [comment]
Waiting for hardware:
one GY-US42 ordered at AliExpress, expected delivery in 15-22 days
According to AliExpress, the GY-US42 is a "replacement" for the SRF02.

**Comment by Christoph-1982** [comment]
Top !

**Comment by Christoph-1982** [comment]
Hi ! Kannst du mir sagen ob du den Ultraschallsensor einbinden wirst ?
