### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by matthesjimte** [UncleSamSwiss/ioBroker.i2c#28]
ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: https://www.npmjs.com/package/iobroker.i2c.npm ERR! package.json npm can't find a package.json file in your current directory.

Installation under console works but will not be showm under iobroker
try  npm init, don't help

**Comment by UncleSamSwiss** [comment]
How did you try to install it? With iobroker.admin and then manually adding the package? It seems like you used the npmjs URL instead of the GitHub URL: https://github.com/UncleSamSwiss/ioBroker.i2c
