### ISSUE TITLE
PCF8574 Outputs not updating

### ISSUE THREAD

**Issue by RustyThePropellerHead** [UncleSamSwiss/ioBroker.i2c#30]
Hello,
I've had to comment out [Lines 136-138 in PCF8574.js](https://github.com/UncleSamSwiss/ioBroker.i2c/blob/edbbe85b1a7ff4c041e983fe26f19cf67a250420/devices/PCF8574.js#L136) to ensure the outputs are being written to the PCF (I have no pins inverted). This also has had the benefit that the unchanged states are being acknowledged in ioBroker. 

Background,
For some reason the 1st Node on the Bus was not being updated after new starts, tried different PCFs and also changing the address (0x20 --> 0x21) with no effect.

Cheers,
Rusty

**Comment by UncleSamSwiss** [comment]
In which situation were the outputs not written to the PCF?

In the start() method there is a sendCurrentValue() and the value is calculated beforehand from the current state values.

The place where you commented out three lines is when setting the value from the outside. There, if the value doesn't change from what is written in start(), I see no reason why we should write it to the  value again (this would occupy the i2c bus for no reason).

**Comment by RustyThePropellerHead** [comment]
True, but in the case of a bus fault, I need to be sure the output is set, otherwise the actuator attached to the output is in an undefined state. I have since used the i2c module in NodeRed due to this module clearing the output byes before writing them (my relays were chattering)... Feel free to close this issue.
