### ISSUE TITLE
advanced feature Interrupt

### ISSUE THREAD

**Issue by falke1987** [UncleSamSwiss/ioBroker.i2c#31]
Hello,

is something planed to add the interrupt feature for the inputs?

Thank you very much in advance.

**Comment by falke1987** [comment]
Hello @UncleSamSwiss do you have any feedback for me? Thank you very much.

**Comment by crycode-de** [comment]
I've already made the pull request #27 to add interrupts in july.

@falke1987 You can install the adapter from my fork via `sudo -H -u iobroker npm install https://github.com/crycode-de/ioBroker.i2c/tarball/master --production --save --prefix "/opt/iobroker"`
Here you get some instructions in German: https://crycode.de/homepi-iobroker-i2c-pcf8574

**Comment by UncleSamSwiss** [comment]
Sorry guys for the long delay, I will have a look at the PR as soon as possible. I'll close this issue, you may track the progress in #27
