### ISSUE TITLE
Support standard kernel interface (IIO)

### ISSUE THREAD

**Issue by andy-shev** [UncleSamSwiss/ioBroker.i2c#32]
I didn't carefully check the code, though it seems it doesn't support native Linux kernel interface to sensors (IIO) via [libiio][1]. Why not to add to cover all in-kernel device drivers at once?

[1]: https://github.com/analogdevicesinc/libiio

**Comment by UncleSamSwiss** [comment]
IIO sounds interesting.

I don't understand yet, which devices would be supported (only ones supported by the kernel?) and if this would be a replacement for i2c or in addition to i2c. 

Do you mind, explaining me a little more what and how I would have to integrate?

**Comment by andy-shev** [comment]
There is a good Wiki page about
https://github.com/analogdevicesinc/libiio/wiki

**Comment by UncleSamSwiss** [comment]
I had a closer look at libIIO and I believe it would most make sense to have a separate adapter, as IIO is not directly related to i2c. IIO Devices can be connected in any way.

As it is easy to create a new adapter and adapters IMHO shouldn't mix technologies, I'd suggest to create a separate adapter if the need arises.
