### ISSUE TITLE
Ask for support of Grove Base HAT for Raspberry

### ISSUE THREAD

**Issue by BigDi** [UncleSamSwiss/ioBroker.i2c#34]
I want to ask for support the Grove Base HAT for Raspberry. It give also a HAT for Raspberry Zero.
[http://wiki.seeedstudio.com/Grove_Base_Hat_for_Raspberry_Pi/](url)
The hardware was found by the adapter...
![grafik](https://user-images.githubusercontent.com/11903065/71300408-cd9d6e00-2394-11ea-8f5d-85e5bf417ac1.png)

**Comment by UncleSamSwiss** [comment]
The Grove Base Hat is only a wiring adapter. Which device do you have plugged into your hat? If it is an I2C device, this adapter might be able to help. If it is one of the other ports (PWM, Analog, GPIO), you would need to use the [rpi2 adapter](https://github.com/iobroker-community-adapters/ioBroker.rpi2).

**Comment by BigDi** [comment]
The grove hat has  a build-in MCU, a 12-bit 8 channel ADC. But I used in the meanwhile an other solution. I added the support for BH1750 and create a pull request.
