### ISSUE TITLE
i2c adapter does not start anymore after updates / node 14 and js-controller 3.3 / Sktiptausführung 5.2.21

### ISSUE THREAD

**Issue by CC1337** [UncleSamSwiss/ioBroker.i2c#390]
**Describe the bug**  
i2C adapter won't start anymore (stays red) with latest js-controller
![grafik](https://user-images.githubusercontent.com/4866744/149925197-3acc6875-35f2-46c2-bda6-3c1c005450d5.png)
javascript adapter update broke it maybe, because I think after that it stopped working.
because I did not do "iobroker update self" before it stopped working, just adapter updates. Or maybe it even was i2c adapter update?

**Versions:**  
 - Adapter version: latest NPM beta or latest github: 1.2.1
 - JS-Controller version: 3.3.2.2
 - Skriptausführung: 5.2.21
 - Node version: 14.8.2
 - Operating system: linux / buanet docker image with node 14

**Comment by UncleSamSwiss** [comment]
After a NodeJS update one needs to rebuild the dependencies. I believe the command is `iobroker rebuild`.

**Comment by CC1337** [comment]
I actually did not do the nodejs update now, it was weeks ago and worked until now, but for some reason it helped
* stopped iobroker
* iobroker rebuild i2c
> npm rebuild --loglevel error (System call1) in "/opt/iobroker/node_modules/iobroker.i2c"
> Rebuild i2c done
* start iobroker again -> similar errors again
![grafik](https://user-images.githubusercontent.com/4866744/149932354-669a4997-8f2d-437e-be40-19b4235f6009.png)
BUT after the iobroker rebuild i2c --install
with the install suffix, IT WORKED!
thank you!
