### ISSUE TITLE
Add Support for APDS-9960

### ISSUE THREAD

**Issue by Telefisch** [UncleSamSwiss/ioBroker.i2c#42]
Hi UncleSam…
Could you please have a look at APDS-9960 Gesture Sensor.
Would be very nice. Thanks

**Comment by UncleSamSwiss** [comment]
I had a look at the APDS-9960 datasheet and it seems rather complicated. Also, there doesn't seem to be any NPM module supporting it. I believe it would be the easiest if you wrote a little application (e.g. in Python) that sends MQTT messages to ioBroker for whatever event you want to get.
