### ISSUE TITLE
Add support for Adafruit STEMMA Soil Sensor

### ISSUE THREAD

**Issue by HB-Git** [UncleSamSwiss/ioBroker.i2c#43]
Hi UncleSam,

It would be nice to have the 'Adafruit STEMMA Soil Sensor - I2C Capacitive Moisture Sensor' supported.

Thank you very much in advance!

Regards,

HB
![image](https://user-images.githubusercontent.com/38045061/81721070-92a0f180-947f-11ea-9635-d3cb89b9fc56.png)

**Comment by UncleSamSwiss** [comment]
The Adafruit STEMMA Soil Sensor is a bit expensive for me to buy simply to add it to the adapter.

If you are still interested in this sensor and are able to help me, we can implement it using the new remote I2C capabilities of the adapter. 

Please let me know if this is an option for you.

**Comment by HB-Git** [comment]
Sure, I can give the best I can! What do you want me to do for this? You can contact me per mail if needed. 
Regards, HB

**Comment by UncleSamSwiss** [comment]
Thanks. Can you please contact me in the ioBroker forum?
https://forum.iobroker.net/user/unclesam
