### ISSUE TITLE
Please add support for MCP3424 

### ISSUE THREAD

**Issue by red-gee** [UncleSamSwiss/ioBroker.i2c#44]
It would be great, if you add support for the MCP3424. 
For me I think it is a better adc than adc1115, because of the output data is in volt, so no need to calculate.

**Comment by red-gee** [comment]
Hi, do you have any good news for me?

**Comment by UncleSamSwiss** [comment]
Sorry, your request was somehow lost.

Waiting for hardware:
one MCP3424 ordered at AliExpress, expected delivery in 30-50 days,
