### ISSUE TITLE
please add support for io plus 8 relais board

### ISSUE THREAD

**Issue by smartboart** [UncleSamSwiss/ioBroker.i2c#49]
The IO-PLUS card share the I2C bus using only two of the Raspberry Pi’s GPIO pins to manage all possible eight cards.  This feature leaves the remaining 24 GPIOs available for the user.

This would be a great feature for your adapter and ioBroker. It would make it easy to use 8 x 8 =  64 relays connected to a raspberrypi while ioBroker is running on it...

here is some more information on github.

https://github.com/SequentMicrosystems/ioplus-rpi

for the moment I switch the relais for example like this with ioBroker javascript...
```js
exec ('ioplus 0  relwr 8 on');
exec ('ioplus 0  relwr 8 off');
```
0 is first bit, so it is  board number 1 ( 0 - 7 bits ) 8 possible  boards and the 8 on and 8 off  is relais number 8.

so in this example we switch on and off Relais number 8 on board 0 ( first board )

It is also possible to read the state of the relais. 
To get feedback:
``` bash
 ioplus 0 relrd 8
```
as feedback you will get a 0 for off and 1 for on.

here the list of possible commands from ioplus-rpi:
```
ioplus -v
        -v              Display the ioplus command version number
        -h              Display the list of command options or one command option details
        -warranty       Display the warranty
        -pinout         Display the board io connector pinout
        -list:          List all ioplus boards connected,return the # of boards and stack level for every board
        board           Display the board status and firmware version number
        relwr:          Set relays On/Off
        relrd:          Read relays status
        reltest:        Turn ON and OFF the relays until press a key
        gpiowr:         Set gpio pins On/Off
        gpiord:         Read gpio status
        gpiodirwr:      Set gpio pins direction I/O  0- output; 1-input
        gpiodirrd:      Read gpio direction 0 - output; 1 - input
        optrd:          Read optocoupled inputs status
        odrd:           Read open drain output pwm value (0% - 100%)
        odwr:           Write open drain output pwm value (0% - 100%), Warning: This function change the output of the coresponded DAC channel
        dacrd:          Read DAC voltage value (0 - 10V)
        dacwr:          Write DAC output voltage value (0..10V), Warning: This function change the output of the coresponded open-drain channel
        adcrd:          Read ADC input voltage value (0 - 3.3V)
        adccal:         Calibrate one ADC channel, the calibration must be done in 2 points at min 2V apart
        adccalrst:      Reset the calibration for one ADC channel
        daccal:         Calibrate one DAC channel, the calibration must be done in 2 points at min 5V apart
        daccalrst:      Reset calibration for one DAC channel
        wdtr:                   Reload the watchdog timer and enable the watchdog if is disabled
        wdtpwr:         Set the watchdog period in seconds, reload command must be issue in this interval to prevent Raspberry Pi power off
        wdtprd:         Get the watchdog period in seconds, reload command must be issue in this interval to prevent Raspberry Pi power off
        wdtipwr:                Set the watchdog initial period in seconds, This period is loaded after power cycle, giving Raspberry time to boot
        wdtiprd:                Get the watchdog initial period in seconds. This period is loaded after power cycle, giving Raspberry time to boot
        wdtopwr:                Set the watchdog off period in seconds (max 48 days), This is the time that watchdog mantain Raspberry turned off
        wdtoprd:                Get the watchdog off period in seconds (max 48 days), This is the time that watchdog mantain Raspberry turned off
        iotst:          Test the ioplus with loopback card inserted
```

**Comment by UncleSamSwiss** [comment]
The ioplus card looks interesting.

I see how you do it with the command line. Unfortunately I'm missing the I2C commands I would have to use to send and receive data. Is there additional documentation on the commands? I can't find anything (except for the actual [C code](https://github.com/SequentMicrosystems/ioplus-rpi/blob/master/ioplus.c)). Currently the NodeRed example also simply uses the command line utility.

If I can send/receive regular I2C commands, I will implement this board, but if it is only possible with the command line utility, that doesn't make sense.

**Comment by UwesSmartHome** [comment]
Hello, can you please find out which I2C Device is on this Relais Boards?
Currently I use solid state Boards from China with I2C expander additionally MCP23017. It is working very well. The issue with Relais is the inrush current with LED Loads because they have a lot of Caps within the Power supply.

**Comment by UwesSmartHome** [comment]
Hello, I did check the schematic of this IO Plus cards as mentioned from smartboart. I could see that I2C has 5V Level, for my understanding there is a need for an Level Shifter to Raspberry 3.3V I2C Interface. 
Smartboart please make a double check for this.
KR Uwe

**Comment by smartboart** [comment]
Hello, no level shifter necessary... I installed it directly... Plug and play.. .. It worked perfect without any other hardware..

**Comment by UncleSamSwiss** [comment]
@smartboart Do you have any additional information about the i2c protocol used by this relay board? If not, I have to close this issue as I'm only going to support devices that I can speak to using i2c commands.

**Comment by smartboart** [comment]
No sorry... I have nothing else... all information I have is from the official github topic...
