### ISSUE TITLE
Is it possible to detect i2c bus on host?

### ISSUE THREAD

**Issue by GermanBluefox** [UncleSamSwiss/ioBroker.i2c#6]

**Comment by UncleSamSwiss** [comment]
Hi @GermanBluefox 
Yes, theoretically it is possible to detect if the device has an I2C bus and then check if there are any supported devices (address ranges), but this would mean we would have to add the I2C dependencies (i2c-bus) to iobroker.discovery, which seems to me a little bit too much just for this adapter.
Also, this adapter is fairly technical; if somebody is tinkering with I2C, she or he will certainly look for an adapter by herself/himself.
I'll close this issue unless you think, I should still do it.
/UncleSam
