### ISSUE TITLE
Permission issue not solved with documented command

### ISSUE THREAD

**Issue by hacki11** [UncleSamSwiss/ioBroker.i2c#68]
**Describe the bug**  
No devices can be found with configured permissions.

**To Reproduce**  
```
sudo chown :i2c /dev/i2c-X
sudo chmod g+rw /dev/i2c-X
sudo usermod -aG i2c iobroker
groups iobroker // shows groups
sudo -u iobroker i2cdetect -y X  // shows successful scan
```
Scan devices results in:
```
2020-11-19 20:26:20.571  - debug: i2c.0 (22972) Searching on current bus 5
2020-11-19 20:26:20.582  - debug: i2c.0 (22972) Search found: []
```

**Expected behavior**  
i2c Adapter will show same numbers in log like found via commandline

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem
![grafik](https://user-images.githubusercontent.com/15319906/99714993-95bc1080-2aa6-11eb-99da-79e58fce501f.png)
.

**Versions:**  
 - Adapter version: github master
 - JS-Controller version: 3.1.6
 - Node version: 14.15.1
 - Operating system: linux

**Additional context**  
My workaround: If i change the owner of i2c-X to iobroker, the adapter finds all the ids

**Comment by UncleSamSwiss** [comment]
You have quite many i2c buses?! OK, but I think the problem is probably the permissions on the i2c-5: if you set it to 'i2c', like the bus 1, it should work as well.

For my curiosity: where do so many i2c buses come from? What tool created it? Can we blame it?

**Comment by hacki11** [comment]
I have a I2C USB Adapter on my Intel Nuc:
 QinHeng Electronics CH341 in EPP/MEM/I2C mode, EPP/I2C adapter
There is only one QMC5883L connected.

It seems i somehow had an node permission issue. Perhaps the group addition wasn't immediately active.
I ran the command https://github.com/Apollon77/ioBroker.smartmeter/issues/168#issuecomment-730656363
`iobroker fix` and now the devices can be accessed by iobroker user from node.

```
juergen@nuc:~$ ls -l /dev/i2c-*
crw-rw---- 1 root i2c 89, 0 Nov 14 14:00 /dev/i2c-0
crw-rw---- 1 root i2c 89, 1 Nov 14 14:00 /dev/i2c-1
crw-rw---- 1 root i2c 89, 2 Nov 14 14:00 /dev/i2c-2
crw-rw---- 1 root i2c 89, 3 Nov 14 14:00 /dev/i2c-3
crw-rw---- 1 root i2c 89, 4 Nov 14 14:00 /dev/i2c-4
crw-rw---- 1 root i2c 89, 5 Nov 14 14:00 /dev/i2c-5
```
