### ISSUE TITLE
Neustart

### ISSUE THREAD

**Issue by itsieber** [UncleSamSwiss/ioBroker.i2c#7]
Hey Uncle Sam

Ich habe das Problem das bei einem neustart des Adapters der MCP irgend welche Zustände bekommt.

Wie kann ich sicherstellen dass er wieder die Zustände bekommt die er haben sollte oder wenigstens alle auf False gehen?

**Comment by UncleSamSwiss** [comment]
Hallo

Hast du die neuste Version des Adapters? Ich habe vor kurzem einige Probleme mit dem Neustart des MCP und des PCF gefixt.

**Comment by itsieber** [comment]
Ich habe soeben gerade die 0.4 überall drauf gespielt..
Ich arbeite negiert. Beim laden des Adapters geht irgendwie (fast) alles auf 1

**Comment by itsieber** [comment]
Hallo Samuel

Ich habe eine Lösung / Workaround gefunden.

devices/MCP23017.js

Zeile 116 add:
`this.writeValue=0;`

**Comment by UncleSamSwiss** [comment]
Danke für deinen Pull Request (und sorry, dass ich mich erst jetzt melde).
Brauchst du den MCP23017 als Input oder Output? Du schreibst nur, dass du negiert arbeitest.
Ich befürchte, dass deine Änderung nicht mehr funktioniert, wenn man nicht negiert arbeitet.

**Comment by UncleSamSwiss** [comment]
No response from @itsieber, closing this issue for now.
